### ISSUE TITLE
Possibly wrong weather forecast data?

### ISSUE THREAD

**Issue by Jpsy** [FL550/dwd_weather#27]
## Version of home_assistant

core-2021.4.6 with Home Assistant OS 5.13 on RPi4b 8Gb

## Version of the custom_component

v1.2.10

## Describe the bug
I am actually not sure, whether something is wrong. But I am creating this issue to give a chance for timely comparison of current weather forecasts:

The current 5 day weather forecast through this custom integration for my region deviates substantially from other reliable forecasts. I am not sure whether this is a normal deviation. Usually DWD is very reliable and the current weather situation is stable and predictable. And up to version 1.2.8 I did not witness such deviations.

Integration settings:
Station-ID J907  = GOLDENE BREMM  
(close to Saarbrücken)

Card settings:
type: weather-forecast
entity: weather.dwd_weather_goldene_bremm

Result in weather card:
![image](https://user-images.githubusercontent.com/1806058/115971415-a33f6000-a548-11eb-91b0-838c203bc9c2.png)

Kachelmann forecast for comparison:
Neither cloud coverage nor temperature profile seem to match.
https://kachelmannwetter.com/de/vorhersage/2842647-saarbruecken/kompakt/deu-hd
![image](https://user-images.githubusercontent.com/1806058/115971431-b6523000-a548-11eb-9bdc-f3c4b208140e.png)

## Debug log

```text

(No conspicuous log entries.)

```

**Comment by Jpsy** [comment]
Here is DWD's own forecast for Saarbrücken as of today. Same discrepancy.

![image](https://user-images.githubusercontent.com/1806058/115985056-54c2ad80-a5aa-11eb-8a1e-714eae10e5c8.png)

HA still shows this:

![image](https://user-images.githubusercontent.com/1806058/115985030-35c41b80-a5aa-11eb-957f-2668bb88da4c.png)

**Comment by FL550** [comment]
Can you please also add the file from https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/J907/kml/MOSMIX_L_LATEST_J907.kmz when you are comparing the forecasts? The forecast is generated from this file.

**Comment by FL550** [comment]
> Here is DWD's own forecast for Saarbrücken as of today. Same discrepancy.
> 
> ![image](https://user-images.githubusercontent.com/1806058/115985056-54c2ad80-a5aa-11eb-8a1e-714eae10e5c8.png)
> 
> HA still shows this:
> 
> ![image](https://user-images.githubusercontent.com/1806058/115985030-35c41b80-a5aa-11eb-957f-2668bb88da4c.png)
> 

This is Saarbrücken Airport, which can be a little different from the station you have selected within HA.

**Comment by Jpsy** [comment]
> Can you please also add the file from https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/J907/kml/MOSMIX_L_LATEST_J907.kmz when you are comparing the forecasts? The forecast is generated from this file.

I'm not sure I understand what I should do. Do you want me to add this file somewhere in HA or next time I report an issue?


> This is Saarbrücken Airport, which can be a little different from the station you have selected within HA.

Yes true, but the distance is 10km and I can actually look over to the airport. There may be a slight difference in temperature. But have you seen the cloud coverage in the forecast? This is what I'm talking about. We have a totally stable high pressure system for the next days all over the region. Blue skies and sun - no trace of clouds anywhere. But the integration shows full cloud coverage for today and 4 days into the future. There is even a heavy discrepancy between within the card itself:

![image](https://user-images.githubusercontent.com/1806058/115989884-dcb3b200-a5c0-11eb-9b22-1dd4d24a9fbc.png)

**Comment by FL550** [comment]
Yes, please upload the file the next time you report the discrepancy.

Ok, maybe I understand the issue. The condition is reported every hour and right now, I scan the conditions for the day and report the worst condition during that time period. So there is possibly one hour where clouds are reported and the integration takes this for the whole day. Maybe I should weight the conditions for the day and show that instead.

**Comment by Jpsy** [comment]
Oh, I see. An interesting problem.
It is not so obvious which algorithm should be used to boil the hourly forecasts down into one single meaningful symbol for the whole day.
Some thoughts from my side:

* Most people will perceive the weather only during daylight hours, probably mostly from 7 am to 8 pm when they are outside and exposed to the weather conditions.
* A first and simple approach might be to simply use the weather symbol that appears most frequently during these daylight hours. 
* BUT: On a day with a sunny morning and a cloudy afternoon it might be much better to chose a sun+cloud symbol, although this symbol might occur in the data only for a short time while the weather changes. So an algorithm that really represents the perceived weather in one symbol, is a challenge.

Doesn't DWD already provide a single symbol for the whole day somewhere in their data? So you wouldn't need to do all the math yourself?

**Comment by Jpsy** [comment]
Here is the current report of Dark Sky for comparison.
It shows EXACTLY the icons that I would expect looking at the detailed data (i.e. of Kachelmann):

![image](https://user-images.githubusercontent.com/1806058/116002501-5916b700-a5fa-11eb-97c5-5604287edd70.png)

Kachelmann to see the detailed prognosis:

![image](https://user-images.githubusercontent.com/1806058/116002617-ece88300-a5fa-11eb-9456-a0d12b4cce00.png)

**Comment by FL550** [comment]
> Doesn't DWD already provide a single symbol for the whole day somewhere in their data? So you wouldn't need to do all the math yourself?

Unfortunately not.

> * Most people will perceive the weather only during daylight hours, probably mostly from 7 am to 8 pm when they are outside and exposed to the weather conditions.
> * A first and simple approach might be to simply use the weather symbol that appears most frequently during these daylight hours.
> * BUT: On a day with a sunny morning and a cloudy afternoon it might be much better to chose a sun+cloud symbol, although this symbol might occur in the data only for a short time while the weather changes. So an algorithm that really represents the perceived weather in one symbol, is a challenge.

I totally aggree with you. Problems on which icons to show appear in many situations. E.g. :
* If it's a sunny day with thunderstorms in the afternoon
* If it's rainy in the morning and after noon sunny

The next problem is, I am limited to these values: https://developers.home-assistant.io/docs/core/entity/weather/#recommended-values-for-state-and-condition

**Comment by FL550** [comment]
Maybe the model can work like this:

1. Count the occurences of each event and take the highest.
2. If there is a at least one hour with significant weather take that.

We then have to define which of the [values](https://www.dwd.de/DE/leistungen/opendata/help/schluessel_datenformate/kml/mosmix_element_weather_xls.xlsx?__blob=publicationFile&v=6) are "significant".

**Comment by Jpsy** [comment]
Maybe it would be much easier to not compile the needed data from already data that is itself already compiled.
What I mean is:
If you have a look at all the graphs in the Kachelmann sample above, you see that it might be much easier to use the graphs at the bottom - cloud coverage and precipitation - to decide what weather the day brings.
It should be quite easy to calculate a medium cloud coverage value over the daylight hours as well as a total precipitation value. These two decide which icons to chose. 
With these two values alone you could already move along the sun/cloud/rain axis of conditions like this:

    sunny -> partlycloudy  -> cloudy -> rainy -> pouring

I am not sure which other elementary data you can build on, but I guess it will not be too difficult to find out if there is rain mixed with snow or only snow. 

Fog, lightning and hail might be more difficult, depending on the raw data.

**Comment by FL550** [comment]
I don't really understand the benefit from using the raw data. I only have aggregated values for every hour. And the condition indicator already tells the most significant weather phenomena within that hour.

**Comment by Jpsy** [comment]
Hi, did you just close this issue or will there be a change to the algorithm? Couldn't find any correlating code changes.

**Comment by FL550** [comment]
Sorry, my fault. 

No I haven't changed the code yet. I am still unsure which method to use.

**Comment by FL550** [comment]
I finally got some time. I have implemented a very basic solution: https://github.com/FL550/simple_dwd_weatherforecast/commit/262c85c08577157073667a863567f431cedb4845

What are your thoughts on this?

**Comment by FL550** [comment]
I just released a [beta](https://github.com/FL550/dwd_weather/tree/v1.2.12-beta) where the change is included. I also requested people to report their experiences with the beta here or in the [HA forum](https://community.home-assistant.io/t/deutscher-wetterdienst-dwd/217488).

**Comment by Jpsy** [comment]
Hi, thanks for working on this issue.
Here are some results from my latest tests.
As you can see the forecast icons are still way off compared to dark sky. Kachelmann diagrams included for comparison.

![Screenshot_20210527-232654](https://user-images.githubusercontent.com/1806058/119899215-21759480-bf43-11eb-91c9-520d42dd8680.png)

![Screenshot_20210527-232017](https://user-images.githubusercontent.com/1806058/119898776-90062280-bf42-11eb-804c-2d291c0f046f.png)

**Comment by FL550** [comment]
In my location it's working as expected right now. I'll keep watching it and I will also release another version tomorrow, which includes debugging messages for the weather condition. Maybe we can then track this down better.

**Comment by larena1** [comment]
Weather still pretty off unfortunately

![Screenshot_20210825-015017](https://user-images.githubusercontent.com/60823161/130704559-c2139115-bc30-4d38-837f-75c9d379d2ce.jpg)

Wasn't sunny at 2 am in the morning, forecast still shows yesterday's weather and rainy vs sunny / cloudy forecast

**Comment by FL550** [comment]
Without further informations I can not find the reason for your discrepancy. 

Please, get your station id, find [the corresponding folder from the dwd server](https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/) and attach the file MOSMIX_L_LATEST_******.kmz to this thread with a screenshot of the forecast which you think is wrong.
